# https://pythonhosted.org/CodeChat/appveyor.yml.html

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  # command to install dependencies
  - python setup.py install
  # also need to download punkt tokeniser data
  - python -m nltk.downloader punkt
  
build: none

test_script:
  # for codecov support
  - pip install pytest pytest-cov
  # command to run tests
  - pytest --cov=./
  
